commuteservicediscovery:
   image:   dockerxya/commute-service-discovery:local
   mem_limit: 1073741824
   ports:
       - "8761:8761"

#configserver:


commuteapigateway:
    image: dockerxya/commute-api-gateway:local
    mem_limit: 1073741824
    ports:
      - "9001:9001"
    links:
      - "commuteservicediscovery:commuteservicediscovery"
    environment:
      PROFILE: "default"
      SERVER_PORT: "9001"
      COMMUTESERVICEDISCOVERY_URI: "http://commuteservicediscovery:8761/eureka/"

commuteauthservice:
    image: dockerxya/commute-auth-service:local
    mem_limit: 1073741824
    ports:
      - "8901:8901"
    links:
      - "commuteservicediscovery:commuteservicediscovery"
      - "commuteapigateway:commuteapigateway"
    environment:
      SERVER_PORT: "8901"
      COMMUTESERVICEDISCOVERY_URI: "http://commuteservicediscovery:8761/eureka/"

commutedirectionsservice:
    image: dockerxya/commute-direction-service:local
    mem_limit: 1073741824
    ports:
      - "8085:8085"
    links:
      - "commuteservicediscovery:commuteservicediscovery"
      - "commuteapigateway:commuteapigateway"
      - "commuteauthservice:commuteauthservice"
    environment:
      SERVER_PORT: "8085"
      COMMUTESERVICEDISCOVERY_URI: "http://commuteservicediscovery:8761/eureka/"
      COMMUTEAUTHSERVICE_USER_URI:   "http://commuteauthservice:8901/auth/api/v1/user"


