commute-service-discovery:
   image:   dockerxya/commute-service-discovery-service:${BUILD_NAME}
   mem_limit: 1073741824
   ports:
       - "8761:8761"

#configserver:


commute-api-gateway:
    image: dockerxya/commute-api-gateway:${BUILD_NAME}
    mem_limit: 1073741824
    ports:
      - "5555:5555"
    links:
      - "commute-auth-service:commute-auth-service"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      EUREKASERVER_URI: "http://commute-auth-service:8761/eureka/"

commute-auth-service:
    image: dockerxya/commute-authentication-service:${BUILD_NAME}
    mem_limit: 1073741824
    ports:
      - "8901:8901"
    links:
      - "commute-service-discovery:commute-service-discovery"
      - "commute-api-gateway:commute-api-gateway"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8901"
      EUREKASERVER_URI: "http://commute-service-discovery:8761/eureka/"

commute-directions-service:
    image: dockerxya/commute-direction-service:${BUILD_NAME}
    mem_limit: 1073741824
    ports:
      - "8085:8085"
    links:
      - "commute-service-discovery:commute-service-discovery"
      - "commute-api-gateway:commute-api-gateway"
      - "commute-auth-service:commute-auth-service"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8085"
      EUREKASERVER_URI: "http://commute-service-discovery:8761/eureka/"
      AUTHSERVER_URI:   "http://commute-auth-service:8901/user"


